### PR TITLE
Add ModernHub for GitHub

### PR DESCRIPTION
**Pull request by BastiaanDeHart**
LINK: https://play.google.com/store/apps/details?id=pw.bastiaan.github

### CODE REVIEW

**Comment by BastiaanDeHart** [comment]
Can you add my Android app please?

**Comment by pcqpcq** [comment]
Of course, but may I ask why don't you [fork](https://github.com/github/android#fork-destination-box) the [origin project](https://github.com/github/android) but create a new project? Or you can make a [pull request](https://github.com/github/android/pulls) to the origin project?

I saw what you did was:
> * The UI is modified (new colors)
> * Small edits
> * BUG fix

Because I think it may be useless if we just do the similar things.

**Comment by BastiaanDeHart** [comment]
But my version in the Google Play store state is up to date while the official GitHub app looks like you are using Android 2.3.5 while mine a Material Design has a a new UI. But when I edit the official GitHub Fork app and then you would want to include on your page please be him.

**Comment by BastiaanDeHart** [comment]
So you would like to add my app to the page please???

**Comment by janisozaur** [comment]
@BastiaanDeHart so for a github application, done in git, you hijacked the source, squashed all of it, violated license (see for example point 4b) and want in for publicity? good joke.

**Comment by BastiaanDeHart** [comment]
According to me it is not forbidden to put the project in the Google Play store and not at all to the source to put back on GitHub and edited.

**Comment by janisozaur** [comment]
your comment lacks/violates some grammar. I have never said it is forbidden, I just mentioned you:
1. violated license, at least in a minor way
2. violated the concept of git in a repository on github, for github and from github. wow, that's quite an achievement, go give yourself a medal.

**Comment by BastiaanDeHart** [comment]
What licenses do I have violated? Because I can edit the source code on GitHub and places so I do not really see the problem and what license I have violated.

**Comment by pcqpcq** [comment]
@BastiaanDeHart I'll merge your pull later if it's ok, I need a little time to checkout your code and what you have done, be patient.

A good stuff is always welcomed, if you are doing the right things, then no one will reject you. Just be patient for a while, please.
Thanks for your pull any way :smile:

**Comment by pcqpcq** [comment]
@BastiaanDeHart 
I am so sorry, but you just change some colors according to [this compare](https://github.com/github/android/compare/master...BastiaanDeHart:master), I don't think it will be helpful to us for now.

**Pull request closed without merging**
