### PR TITLE
add zhihu kotlin

### PR DESCRIPTION
**Pull request by xu6148152**

### CODE REVIEW

**Comment by pcqpcq** [comment]
Its **Major Language**  is **Kotlin**, not **Java**, please fix this first, thanks.


On the other hand, it includes some bugs... 
A good start, any way.

**Comment by xu6148152** [comment]
@pcqpcq  I have updated it yet.

**Comment by pcqpcq** [comment]
ok, thanks!

nice repo, i will watch it :smile:

**Comment by lzyzsd** [comment]
@pcqpcq thanks。I am still working on it, I plan to post about this repo after most functions finished.

**Comment by pcqpcq** [comment]
:+1: 
I've cloned the repo and read the code, maybe we can work together later :smile:

**Comment by lzyzsd** [comment]
welcome

**Pull request merged**
