### PR TITLE
Pi by @rigobertomolina

### PR DESCRIPTION
**Pull request by rigobertomolina**

### CODE REVIEW

**Comment by rigobertomolina** [comment]
Why are everyone's builds failing?

**Comment by rigobertomolina** [comment]
Seems like the problem is that some links are not available anymore.

**Comment by Swati4star** [comment]
Check this PR (https://github.com/pcqpcq/open-source-android-apps/pull/173) 
I have removed all the bad links. The build is passing in this case.

**Comment by rigobertomolina** [comment]
I'll make another PR.

**Pull request closed without merging**
