### PR TITLE
Added 2 new open-source projects

### PR DESCRIPTION
**Pull request by jemboy**
Added a project called Buddy Navigator under the category "Travel and Local" and added "a project called Interval Timer under the category "Tools".

### CODE REVIEW

**Comment by pcqpcq** [comment]
thanks for your pr.
I can't merge them, but I will keep my eyes on these. :smile:

**Comment by jemboy** [comment]
I will not be developing them any further for now. Why can't you merge them?

**Comment by epicstar** [comment]
You should just take what @jemboy and merge those conflicts...

**Comment by pcqpcq** [comment]
fine, i've read your code.
i'll merge them, but i don't think they are useful...
maybe i will remove them later, sorry.

**Pull request merged**
